title: "Caspar15 的網站"
description: "這是一個使用 Jekyll 建立的 GitHub Pages 網站"
baseurl: ""                  # 因為是 user page (caspar15.github.io)，留空即可
url: "https://caspar15.github.io"

# markdown 引擎
markdown: kramdown

# 外掛 (可依需求增刪)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 要忽略不上傳的檔案
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - .gitignore
  - .idea
  - .vscode
