title: "Caspar15 的網站"
description: "這是一個使用 Jekyll 建立的 GitHub Pages 網站"
baseurl: ""                  # 因為是 user page (caspar15.github.io)，留空即可
url: "https://caspar15.github.io"

# 使用 kramdown 作為 Markdown 引擎
markdown: kramdown

# 外掛
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:name

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - .gitignore
  - .idea
  - .vscode

# 設定永久連結 (專案頁面 URL 將會是 /projects/greenfriend/ 形式)
permalink: /:categories/:title/

# 摘要分隔符號
excerpt_separator: <!-- excerpt -->
